---
title: "NCA Timber: Pilot Accounts for the Great Lakes and Southern U.S."
output: html_notebook
---
```{r, results = 'hide', message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)

# Function to convert price from cords to MBF
convert_price_cord_mbf <- function(price_per_cord) {
  # Conversion factors
  board_feet_per_cord <- 500
  board_feet_per_mbf <- 1000
  
  # Calculate price per board foot
  price_per_board_foot <- price_per_cord / board_feet_per_cord
  
  # Calculate price per MBF
  price_per_mbf <- price_per_board_foot * board_feet_per_mbf
  
  return(price_per_mbf)
}

# Function to convert price from MBF to tons
convert_price_mbf_tons <- function(price_per_mbf) {
  # Conversion factor
  tons_per_mbf <- 2.4
  
  # Calculate price per ton
  price_per_ton <- price_per_mbf / tons_per_mbf
  
  return(price_per_ton)
}
```

# Define the species groups to be included in the timber asset account pilot

## Load FIA data

FIA data is from the 2020 evaluation which includes observation made from 2015-2020

```{r, echo=F}
stateName <- c('1' = 'Alabama',
                 '5' = 'Arkansas',
                 '12' = 'Florida',
                 '13' = 'Georgia',
                 '22' = 'Louisiana',
                 '26' = 'Michigan',
                 '27' = 'Minnesota',
                 '28' = 'Mississippi',
                 '37' = 'North Carolina',
                 '45' = 'South Carolina',
                 '47' = 'Tennessee',
                 '48' = 'Texas',
                 '55' = 'Wisconsin',
                 '51' = 'Virginia')

stateRegion <- c('Alabama' = 'South',
                 'Arkansas' = 'South',
                 'Florida' = 'South',
                 'Georgia' = 'South',
                 'Louisiana' = 'South',
                 'Mississippi' = 'South',
                 'North Carolina' = 'South',
                 'South Carolina' = 'South',
                 'Tennessee' = 'South',
                 'Texas' = 'South',
                 'Virginia' = 'South',
                 'Michigan' = 'Great Lakes',
                 'Minnesota' = 'Great Lakes',
                 'Wisconsin' = 'Great Lakes')

spgr.area <- read.csv("nca-species-group-list.csv") %>%
  group_by(SPGRPNM, COUNTYCD, STATECD, UNITCD) %>%
  summarize(AREA = sum(AREATOT, na.rm = T), .groups = 'drop') %>%
  mutate(STATENM = stateName[as.character(STATECD)],
         REGION = stateRegion[STATENM])

spgr.list <- spgr.area %>%
  group_by(SPGRPNM, REGION) %>%
  summarize(AREA = sum(AREA, na.rm = T) / 1000, .groups = 'drop') %>%
  arrange(desc(REGION), desc(AREA))

kable(spgr.list,
      caption = "Timber Account Species Groups by Region",
      col.names = c("Species Group", "Region", "Area (1000 acres)"),
      align = "lcc", digits = 0)
```

# load the biomass data from FIA


```{r}

biomass <- read.csv("nca-timber-biomass.csv") %>%
  select(-c('RESERVCD', 'EVALID'))

names(biomass) <- c('STATENM', 'STATECD', 'COUNTYNM', 'COUNTYCD', 'SPGRPCD',
                    'SPGRPNM','SPCLASS', 'UNITCD','3', '4', '5', '6',
                    '7', '8', '9', '10', '11', '12', '13', '14', '15',
                    '16', '17', '18', '19', '20', '21')

sizeClass <- c('3' = '5-6.9 inches',
               '4' = '7-8.9 inches',
               '5' = '9-10.9 inches',
               '6' = '11-12.9 inches',
               '7' = '13-14.9 inches',
               '8' = '15-16.9 inches',
               '9' = '17-18.9 inches',
               '10' = '19-20.9 inches',
               '11' = '21-22.9 inches',
               '12' = '23-24.9 inches',
               '13' = '25-26.9 inches',
               '14' = '27-28.9 inches',
               '15' = '29-30.9 inches',
               '16' = '31-32.9 inches',
               '17' = '33-34.9 inches',
               '18' = '35-36.9 inches',
               '19' = '37-38.9 inches',
               '20' = '39-40.9 inches',
               '21' = '41+ inches')

biomass <- biomass %>%
  pivot_longer(cols = 9:27,
                names_to = 'sizeClassCode',
                values_to = 'biomass') %>%
  mutate(biomass = ifelse(is.na(biomass), 0, biomass),
         sizeClass = sizeClass[sizeClassCode])


```

```{r}
# create a table that shows the distribution of biomass by size class and state
biomass.table <- biomass %>%
  group_by(STATENM, SPGRPNM, sizeClass) %>%
  summarise(totalBiomass = round(sum(biomass)/1000000, digits = 1), .groups = 'drop') %>%
  pivot_wider(names_from = sizeClass, values_from = totalBiomass) %>%
  rename('State' = STATENM, 'Species Group' = SPGRPNM) %>%
  select(State, 'Species Group', '5-6.9 inches', '7-8.9 inches', '9-10.9 inches',
         '11-12.9 inches', '13-14.9 inches', '15-16.9 inches', '17-18.9 inches',
         '19-20.9 inches', '21-22.9 inches', '23-24.9 inches', '25-26.9 inches',
         '27-28.9 inches', '29-30.9 inches', '31-32.9 inches', '33-34.9 inches',
         '35-36.9 inches', '37-38.9 inches', '39-40.9 inches', '41+ inches')

kable(biomass.table,
      caption = "Timber Account Biomass by Species Group, Size Class, and State/n(million tons)",
      digits = 1)
```

# Organize the price data


```{r}

library(readxl)
tmnPrices <- suppressWarnings(read_excel("TMN_Price_Series_September2023.xlsx")) %>%
  filter(Market == 'Stumpage',
         Region %in% c('MI','MN','WI'),
         Species != 'Sawtimber ($/mbf)') %>%
  rename(State = `Region`,
         priceRaw = `$ Per Unit`) %>%
  mutate(priceTons = ifelse(Units == 'mbf',
                            convert_price_mbf_tons(priceRaw),
                            convert_price_mbf_tons(convert_price_cord_mbf(priceRaw))),
         month = as.integer(format(tmnPrices$`Period End Date`, "%m")),
         year = as.integer(format(tmnPrices$`Period End Date`, "%Y"))) %>%
  select(-c('Market', 'Units', 'priceRaw', 'Period End Date'))

# make a kable table with average prices for each species and state
tmnPrices.table <- tmnPrices %>%
  group_by(State, Species, Product) %>%
  summarize(Price = mean(priceTons), .groups = 'drop') %>%
  arrange(Species)

kable(tmnPrices.table,
      caption = "Great Lakes: Timber Account Stumpage Prices by State and Species",
      col.names = c("State", "Species", "Product", "Average Price"),
      digits = 2)

```


```{r}
# print the list of unique species in alphabetical order from merchBIO using SPGRPNM
merchBio %>% select(SPGRPNM) %>% unique() %>% arrange(SPGRPNM)
```
```{r}
# create a crosswalk between tmnPrices$Species and merchBio$SPGRPNM
# this will allow us to join
crosswalk <- tribble(
  ~SPGRPNM, ~Species,
  'Ash', 'Ash',
  'Basswood', 'Basswood',
  'Beech', 'Beech',
  'Black Walnut', 'Black Walnut',
  'Cottonwood and aspen (East)', 'Aspen', 
  'Eastern hemlock', 'Hemlock', 
  'Eastern white and red pines', 'White Pine',
  'Eastern white and red pines', 'Red Pine',
  'Hard maple', 'Maple',
  'Hickory', 'Hickory',
  'Jack pine', 'Jack Pine',
  'Loblolly and shortleaf pines', '',
  'Other eastern hard hardwoods', '',
  'Other eastern soft hardwoods', '',
  'Other eastern softwoods', '',
  'Other red oaks', '',
  'Other white oaks', '',
  'Select red oaks', 'Red Oak',
  'Select white oaks', 'White Oak',
  'Soft maple', 'Soft Maple',
  'Spruce and balsam fir', 'Spruce',
  'Spruce and balsam fir', 'Spruce/Fir',
  'Tupelo and blackgum', '',
  'Yellow-poplar', '',
  'Yellow birch', 'Yellow Birch')
  

```



# Organize the FIA data

```{r}
# join the two dataframes
df <- left_join(merchBio, premerchBio, by = c('STATENM','STATECD', 'COUNTYNM',
                                              'COUNTYCD', 'SPGRPCD', 'SPGRPNM',
                                              'SPCLASS', 'UNITCD', 'EVALID',
                                              'RESERVCD'))

# pivot longer on columns 11 to 33
# drop if biomass is NA
df <- df %>% pivot_longer(cols = 11:33,
                          names_to = 'sizeClass',
                          values_to = 'biomass') %>%
            filter(!is.na(biomass))

```

```{r}
# join prices to df
df <- left_join(df, tmnPrices, by = c('SPGRPCD' = 'Species'))
```


