# create a dictionary with fia code, species name, species family, and market region
# use the fia code as the key
# use the species name, species family, and market region as the values
# market region is either 'Great Lakes' or 'South'
timberSpecies = {'012': ['balsam fir', 'Pine', 'Great Lakes'],
                 '086': ['eastern redcedar', 'Cypress', 'Great Lakes, South'],
                 '071': ['tamarack', 'Pine', 'Great Lakes'],
                    '091': ['Norway spruce', 'Pine', 'Great Lakes'],
                    '094': ['white spruce', 'Pine', 'Great Lakes'],
                    '095': ['black spruce', 'Pine', 'Great Lakes'],
                    '105': ['jack pine', 'Pine', 'Great Lakes'],
                    '110': ['shortleaf pine', 'Pine', 'South'],
                     '111': ['slash pine', 'Pine', 'South'],
                     '121': ['longleaf pine', 'Pine', 'South'],
                     '125': ['red pine', 'Pine', 'Great Lakes'],
                     '126': ['pitch pine', 'Pine', 'Great Lakes'],
                     '129': ['eastern white pine', 'Pine', 'Great Lakes, South'],
                     '130': ['Scotch (Scots) pine', 'Pine', 'Great Lakes'],
                     '131': ['loblolly pine', 'Pine', 'South'],
                     '132': ['Virginia pine', 'Pine', 'South'],
                     '221': ['baldcypress', 'Cypress', 'South'],
                     '313': ['boxelder', 'Maple', 'Great Lakes'],
                     '314': ['black maple', 'Maple', 'Great Lakes, South'],
                     '316': ['red maple', 'Maple', 'Great Lakes'],
                     '318': ['sugar maple', 'Maple', 'Great Lakes, South'],
                     '371': ['yellow birch', 'Birch', 'Great Lakes'],
                     '375': ['paper birch', 'Birch', 'Great Lakes'],
                     '409': ['mockernut hickory', 'Walnut', 'South'],
                     '402': ['bitternut hickory', 'Walnut', 'Great Lakes, South'],
                     '403': ['pignut hickory', 'Walnut', 'South'],
                     '404': ['pecan', 'Walnut', 'South'],
                     '405': ['shelbark hickory', 'Walnut', 'South'],
                     '407': ['shagbark hickory', 'Walnut', 'South'],
                     '462': ['hackberry', 'Elm', 'Great Lakes'],
                     '531': ['American beech', 'Beech', 'Great Lakes'],
                     '541': ['white ash', 'Olive', 'Great Lakes, South'],
                     '543': ['black ash', 'Olive', 'Great Lakes'],
                     '544': ['green ash', 'Olive', 'Great Lakes, South'],
                     '546': ['blue ash', 'Olive', 'Great Lakes, South'],
                     '601': ['butternut', 'Walnut', 'South'],
                     '602': ['black walnut', 'Walnut', 'Great Lakes, South'],
                     '611': ['sweetgum', 'Witch-hazel', 'South'],
                     '621': ['yellow-poplar', 'Magnolia', 'South'],
                     '651': ['cucubertree', 'Magnolia', 'South'],
                     '652': ['southern magnolia', 'Magnolia', 'South'],
                     '653': ['sweetbay', 'Magnolia', 'South'],
                     '742': ['eastern cottonwood', 'Willow', 'Great Lakes'],
                     '743': ['bigtooth aspen', 'Willow', 'Great Lakes'],
                     '746': ['quaking aspen', 'Willow', 'Great Lakes'],
                     '762': ['black cherry', 'Rose', 'Great Lakes, South'],
                     '802': ['white oak', 'Beech', 'Great Lakes, South'],
                     '804': ['swamp white oak', 'Beech', 'Great Lakes, South'],
                     '809': ['northern pin oak', 'Beech', 'Great Lakes'],
                     '812': ['southern red oak', 'Beech', 'South'],
                     '822': ['overcup oak', 'Beech', 'South'],
                     '823': ['bur oak', 'Beech', 'Great Lakes, South'],
                     '826': ['chinkapin oak', 'Beech', 'Great Lakes'],
                     '830': ['pin oak', 'Beech', 'South'],
                     '832': ['chestnut oak', 'Beech', 'South'],
                     '833': ['northern red oak', 'Beech', 'Great Lakes'],
                     '837': ['black oak', 'Beech', 'Great Lakes, South'],
                     '951': ['American basswood', 'Linden', 'Great Lakes'],
                     '972': ['American elm', 'Elm', 'Great Lakes'],
                     '977': ['rock elm', 'Elm', 'Great Lakes']
                     }