import pandas as pd

# Species dictionary
speciesDict = {
    12: 'balsim fir',
    68: 'eastern redcedar',
    71: 'tamarack',
    91: 'Norway spruce',
    94: 'white spruce',
    95: 'black spruce',
    105: 'jack pine',
    110: 'shortleaf',
    111: 'slash',
    121: 'longleaf',
    125: 'red pine',
    129: 'eastern white pine',
    130: 'Scotch pine',
    131: 'loblolly',
    132: 'Virginia pine',
    221: 'baldcypress',
    313: 'boxelder',
    316: 'red maple',
    318: 'sugar maple',
    371: 'yellow birch',
    375: 'paper birch',
    402: 'butternut hickory',
    403: 'pignut hickory',
    404: 'pecan',
    405: 'shelbark hickory',
    407: 'shagbark hickory',
    409: 'mockernut hickory',
    462: 'hackberry',
    531: 'American beech',
    541: 'white ash',
    543: 'black ash',
    544: 'green ash',
    546: 'blue ash',
    601: 'butternut',
    602: 'black walnut',
    611: 'sweetgum',
    621: 'yellow-poplar',
    651: 'cucumber tree',
    652: 'southern magnolia',
    653: 'sweetbay',
    742: 'eastern cottonwood',
    743: 'bigtooth aspen',
    746: 'quaking aspen',
    762: 'black cherry',
    802: 'white oak',
    809: 'northern pin oak',
    812: 'southern red oak',
    822: 'overcup oak',
    830: 'pin oak',
    833: 'northern red oak',
    951: 'American basswood',
    972: 'American elm',
}

def get_species_name(spcd):
    """Return the species name for a given code."""
    return speciesDict.get(spcd, None)

speciesGroupDict = {
    1: 'Longleaf and slash pines',
    2: 'Lobolly and shortleaf pines',
    3: 'Other yellow pines',
    4: 'Eastern white and red pines',
    5: 'Jack pine',
    6: 'Spruce and balsam fir',
    7: 'Eastern hemlock',
    8: 'Cypress',
    9: 'Other eastern softwoods',
    23: 'Woodland softwoods',
    25: 'Select white oaks',
    26: 'Select red oaks',
    27: 'Other white oaks',
    28: 'Other red oaks',
    29: 'Hickory',
    30: 'Yellow birch',
    31: 'Hard maple',
    32: 'Soft maple',
    33: 'Beech',
    34: 'Sweetgum',
    35: 'Tupelo and blackgum',
    36: 'Ash',
    37: 'Cottonwood and aspen',
    38: 'Basswood',
    39: 'Yellow-poplar',
    40: 'Black walnut',
    41: 'Other eastern soft hardwoods',
    42: 'Other eastern hard hardwoods',
    43: 'Eastern noncommericial hardwoods',
}

def get_species_group_name(spgrpcd):
    """Return the species group name for a given code."""
    return speciesGroupDict.get(spgrpcd, None)

# Add more shared utility functions as needed 